services:
    _defaults:
        autoconfigure: true
        autowire: true

    # Migration
    ContaoThemesNet\OddThemeBundle\Migration\:
        resource: "../../Migration/*"
        tags:
            - { name: contao.migration, priority: 99 }
