services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]

        Symfony\Component\DependencyInjection\ContainerAwareInterface:
            calls:
                - ["setContainer", ["@service_container"]]

    # Migration
    ContaoThemesNet\OddThemeBundle\Migration\:
        resource: "../src/Migration/*"
        arguments:
            - '@contao.framework'
            - '@database_connection'
        tags:
            - { name: contao.migration, priority: 99 }
